export { default as Home } from './Home'
export { default as Products } from './Products'
export { default as Location } from './Location'
export { default as About } from './About'
export { default as Contact } from './Contact'
